## 二、Numpy基础
### 1.np数组的构造

In [2]:
# 最一般的方式是通过array来构造
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [3]:
# 下面讨论一些特殊数组的生成方式
# a.等差序列：np.linspace;np.arange
np.linspace(1,5,11) # 起始、终止（包含）、样本个数

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [4]:
np.arange(1,5,2) # 起始、终止（不包含）、步长

array([1, 3])

In [5]:
# b.特殊矩阵：zeros, eye, full
np.zeros((2,3)) # 传入元组表示各维度大小

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.eye(3) # 3*3的单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
np.eye(3,k = 1) # 偏移主对角线1个单位的伪单位矩阵

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [8]:
np.full((2,3),10) # 元组传入大小,10为填充值

array([[10, 10, 10],
       [10, 10, 10]])

In [9]:
np.full((2,3),[1,2,3]) # 每行填入相同的列表

array([[1, 2, 3],
       [1, 2, 3]])

In [10]:
# c.随机矩阵: np.random
# 最常用的随机生成函数为rand,randn, randint,choice,它们分别表示0-1均匀分布的随机数组，标准正态分布的随机数组，随机整数组和随机列表抽样：
np.random.rand(3) # 3个0-1均匀分布的随机数

array([0.5819963 , 0.96856315, 0.04802621])

In [11]:
np.random.rand(3,3) # 3*3的0-1均匀分布随机矩阵

array([[0.98192951, 0.86159846, 0.06302107],
       [0.61361005, 0.50778982, 0.88628674],
       [0.30355022, 0.00121619, 0.874001  ]])

In [12]:
# 对于服从区间a到b上的均匀分布可以如下生成：
a, b = 5, 15
(b-a) * np.random.rand(3) + a  # 3个服从a到b均匀分布的随机数

array([ 7.88745033,  9.78956514, 14.4452174 ])

In [13]:
# 一般地，可以选择已有的库函数：
np.random.uniform(5,15,3)  # 3个服从5到15均匀分布的随机数

array([11.16709083, 13.1038782 ,  9.24373679])

In [14]:
# randn生成N(0,1)的标准正态分布:
np.random.randn(3)

array([ 0.79994571, -0.69969737,  0.72101801])

In [15]:
np.random.randn(2,2) # 2*2标准正态分布随机矩阵

array([[-1.09921927,  0.68731405],
       [-0.04276146, -1.14687943]])

In [16]:
# 对于服从方差为σ²，均值为μ的正态分布N(μ,σ²)的随机数，可以通过如下变换得到：
sigma, mu = 2.5, 3
mu + sigma * np.random.randn(3)

array([5.31658439, 5.25098012, 6.21887194])

In [17]:
# 同样的，也可以通过已有的库函数生成：
np.random.normal(3,2.5,3)  # 3个服从N(3,2.5²)的随机数

array([2.9035793 , 3.87204808, 6.3424893 ])

In [18]:
# randint可以指定生成随机整数的最小值最大值（不包含）和维度大小：
low, high, size = 5, 15, (2,2) # 生成2*2的5到14之间的随机整数矩阵
np.random.randint(low, high, size)

array([[11,  5],
       [11,  7]], dtype=int32)

In [19]:
# choice可以从给定的列表中，以一定概率和方式抽取结果，当不指定概率时为均匀采样，默认抽取方式为有放回抽样：
my_list = ['a','b','c','d']
np.random.choice(my_list, 2, replace = False, p = [0.1,0.7,0.1,0.1]) # 从my_list中无放回抽取2个元素，且'b'被抽中的概率为0.7

array(['c', 'b'], dtype='<U1')

In [20]:
np.random.choice(my_list,(3,3)) # 有放回抽取3*3元素矩阵

array([['a', 'b', 'a'],
       ['a', 'd', 'd'],
       ['d', 'c', 'a']], dtype='<U1')

In [21]:
# 当返回的元素个数与原列表相同时，不放回抽样等价于使用permutation函数，即打散原列表：
np.random.permutation(my_list)

array(['d', 'b', 'a', 'c'], dtype='<U1')

In [22]:
# 最后需要提到的是随机种子，它能够固定随机数的输出结果:
np.random.seed(0)
np.random.rand()

0.5488135039273248

In [23]:
np.random.seed(0)
np.random.rand()

0.5488135039273248

### 2.np数组的变形与合并

In [24]:
# [a] 转置：T
np.zeros((2,3)).T

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
# [b] 合并操作：r_ , c_,分别沿第一轴和第二轴进行合并
# 对二维数组而言，r_和c_分别表示上下合并和左右合并:
np.r_[np.zeros((2,3)), np.zeros((2,3))] # 上下合并，结果为4*3矩阵

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [26]:
np.c_[np.zeros((2,3)), np.zeros((2,3))] # 左右合并，结果为2*6矩阵

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [27]:
# 一维数组和二维数组进行合并时，应当把其视作列向量，在长度匹配的情况下只能够使用左右合并的c_操作：
try:
    np.r_[np.array([0,0]), np.zeros((2,1))] 
except Exception as e:
    Err_Msg = e
Err_Msg

ValueError('all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)')

In [28]:
np.r_[np.array([0,0]), np.zeros(2)] 

array([0., 0., 0., 0.])

In [ ]:
np.c_[np.array([0,0]),np.zeros((2,3))] 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [31]:
# [c] 维度变换：reshape
# reshape能够帮助用户把原数组按照新的维度重新排列。在使用时，有两种模式，分别为C模式和F模式，分别以逐行和逐列的顺序进行填充读取。
target = np.arange(8).reshape(2,4) 
target

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [ ]:
target.reshape((4,2), order='C')  # C模式，逐行读取和填充  order='C'为默认值

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [33]:
target.reshape((4,2), order='F') # F模式，逐列读取和填充

array([[0, 2],
       [4, 6],
       [1, 3],
       [5, 7]])

In [34]:
# 特别地，由于被调用数组的大小是确定的，reshape允许有一个维度存在空缺,此时只需填充-1即可：
target.reshape((4,-1))

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7]])

In [35]:
# 下面将n*1大小的数组转为1维数组的操作是经常使用的:
target = np.ones((3,1))
target

array([[1.],
       [1.],
       [1.]])

In [36]:
target.reshape(-1)

array([1., 1., 1.])

### 3.np数组的切片与索引

In [37]:
# 数组的切片模式支持使用slice类型的start:end:step切片,还可以直接传入列表指定某个维度的索引进行切片:
target = np.arange(9).reshape(3,3)
target

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [41]:
target[:-1, [0,2]]

array([[0, 2],
       [3, 5]])

In [42]:
# 此外，还可以利用np.ix_在对应的维度上使用布尔索引，但此时不能使用slice切片:
target[np.ix_([True, False, True], [True, False, True])]

array([[0, 2],
       [6, 8]])

In [43]:
target[np.ix_([1,2], [True, False, True])]

array([[3, 5],
       [6, 8]])

In [44]:
# 当数组维度为1维时，可以直接进行布尔索引，而无需np.ix_:
new = target.reshape(-1)
new[new%2==0]

array([0, 2, 4, 6, 8])

### 4.常用函数

In [45]:
# 为了简单起见，这里假设下述函数输入的数组都是一维的
# [a] where, where是一种条件函数，可以指定满足条件与不满足条件位置对应的填充值:
a = np.array([-1,1,-1,0])
np.where(a>0, a, 5) # 对应位置为True时填充a对应元素，否则填充5

array([5, 1, 5, 5])

In [46]:
# [b] nonzero, argmax, argmin
# 这三个函数返回的都是索引， nonzero返回非零数的索引， argmax，argmin分别返回最大和最小数的索引：
a = np.array([-2,-5,0,1,3,-1])
np.nonzero(a)

(array([0, 1, 3, 4, 5]),)

In [47]:
a.argmax()

np.int64(4)

In [48]:
a.argmin()

np.int64(1)

In [49]:
# [c] any, all
# any指当序列至少存在一个True或非零元素时返回True,否则返回False
# all指当序列元素全为True或非零元素时返回True,否则返回False
a = np.array([0,1])
a.any()

np.True_

In [50]:
a.all()

np.False_

In [51]:
# [d] cumprod, cumsum, diff
# cumprod, cumsum分别表示累乘和累加函数,返回同长度的数组, diff表示和前一个元素做差,由于第一个元素为缺失值，因此在默认参数情况下，返回长度是原数组减1
a = np.array([1,2,4])
a.cumprod()

array([1, 2, 8])

In [52]:
a.cumsum()

array([1, 3, 7])

In [53]:
np.diff(a)

array([1, 2])

In [54]:
# [e] 统计函数
# 常用的统计函数包括max, min, mean, median, std, var, sum, quantile,其中分位数计算是全局方法，因此不能通过array.quantile的方法调用：
target = np.arange(5)
target

array([0, 1, 2, 3, 4])

In [55]:
target.max()

np.int64(4)

In [ ]:
np.quantile(target, 0.5) # 0.5分位数  

np.float64(2.0)

In [58]:
# 但是对于含有缺失值的数组,它们返回的结果也是缺失值，如果需要略过缺失值，必须使用nan*类型的函数，上述的几个统计函数都有对应的nan*函数
target = np.array([1,2,np.nan])
target

array([ 1.,  2., nan])

In [61]:
target.max()

np.float64(nan)

In [62]:
np.nanmax(target)

np.float64(2.0)

In [63]:
np.nanquantile(target, 0.5)

np.float64(1.5)

In [ ]:
# 对于协方差和相关系数分别可以利用cov, corrcoef如下计算：
target1 = np.array([1,3,5,9])
target2 = np.array([1,5,3,-9])
np.cov(target1, target2)  # 协方差矩阵

array([[ 11.66666667, -16.66666667],
       [-16.66666667,  38.66666667]])

In [65]:
np.corrcoef(target1, target2)  # 相关系数矩阵

array([[ 1.        , -0.78470603],
       [-0.78470603,  1.        ]])

In [66]:
# 最后，需要说明二维Numpy数组中统计函数的axis参数，它能够进行某一个维度下的统计特征计算，当axis=0时结果为列的统计指标，当axis=1时结果为行的统计指标:
target = np.arange(1,10).reshape(3,-1)
target

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [67]:
target.sum(axis = 0)

array([12, 15, 18])

In [69]:
target.sum(axis = 1) 

array([ 6, 15, 24])

### 5.广播机制
广播机制用于处理两个不同维度数组之间的操作，这里只讨论不超过两维的数组广播机制

In [70]:
# [a] 标量和数组的操作
# 当一个标量和数组进行运算时，标量会自动把大小扩充为数组大小，之后进行逐元素操作：
res = 3 * np.ones((2,2)) + 1
res

array([[4., 4.],
       [4., 4.]])

In [71]:
res = 1 / res
res

array([[0.25, 0.25],
       [0.25, 0.25]])

In [72]:
# [b] 二维数组之间的操作
# 当两个数组维度完全一致时，使用对应元素的操作，否则会报错，除非其中的某个数组的维度是m*1或者1*n,那么会扩充其具有1的维度为另一个数组对应维度的大小
# 例如，1*2数组和3*2数组做逐元素运算时会把第一个数组扩充为3*2数组，扩充时的对应数值进行赋值。但是，需要注意，如果第一个数组的维度是1*3，那么由于在第二维上的大小不匹配且不为1，此时报错
res = np.ones((3,2))
res

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [ ]:
res * np.array([[2,3]]) # 第二个数组扩充第一维度为3

array([[2., 3.],
       [2., 3.],
       [2., 3.]])

In [74]:
res * np.array([[2],[3],[4]]) # 第二个数组扩充第二维度为2

array([[2., 2.],
       [3., 3.],
       [4., 4.]])

In [77]:
res * np.array([[2]])  # 等价于两次扩充，第二个数组两个维度分别扩充为3和2

array([[2., 2.],
       [2., 2.],
       [2., 2.]])

In [78]:
# [c] 一维数组与二维数组的操作
# 当一维数组A_k 与 二维数组B_m,n操作时，等价于把一维数组视为A_1,k的二维数组，使用的广播法则与[b]中一致，当k! = n 且 k，n都不是1时报错
np.ones(3) + np.ones((2,3))

array([[2., 2., 2.],
       [2., 2., 2.]])

In [81]:
np.ones(3) + np.ones((2,1))

array([[2., 2., 2.],
       [2., 2., 2.]])

In [82]:
np.ones(1) + np.ones((2,3))

array([[2., 2., 2.],
       [2., 2., 2.]])

### 6.向量与矩阵计算

In [83]:
# [a] 向量内积: dot
a = np.array([1,2,3])
b = np.array([1,3,5])
a.dot(b)

np.int64(22)

In [ ]:
# [b] 向量范数和矩阵范数: np.linalg.norm
# 在矩阵范数的计算中，最重要的是ord参数

![ord参数可选值](./PixPin_2025-10-21_14-30-58.png)

In [84]:
matrix_target = np.arange(4).reshape(-1,2)
matrix_target

array([[0, 1],
       [2, 3]])

In [85]:
np.linalg.norm(matrix_target, ord='fro')

np.float64(3.7416573867739413)

In [86]:
np.linalg.norm(matrix_target, np.inf)

np.float64(5.0)

In [87]:
np.linalg.norm(matrix_target, ord=2)

np.float64(3.702459173643833)

In [89]:
vector_target = np.arange(4)
vector_target

array([0, 1, 2, 3])

In [90]:
np.linalg.norm(vector_target, np.inf)

np.float64(3.0)

In [91]:
np.linalg.norm(vector_target, ord = 2)

np.float64(3.7416573867739413)

In [92]:
np.linalg.norm(vector_target, ord = 3)

np.float64(3.3019272488946263)

In [93]:
# [c] 矩阵乘法: @
a = np.arange(4).reshape(-1,2)
a

array([[0, 1],
       [2, 3]])

In [94]:
b = np.arange(-4,0).reshape(-1,2)
b

array([[-4, -3],
       [-2, -1]])

In [95]:
a@b

array([[ -2,  -1],
       [-14,  -9]])

### 三、练习

In [99]:
# Ex1:利用列表推导式实现矩阵乘法
[[sum(a[i,k] * b[k,j] for k in range(a.shape[1])) for j in range(b.shape[1])] for i in range(a.shape[0])]

[[np.int64(-2), np.int64(-1)], [np.int64(-14), np.int64(-9)]]

In [106]:
# Ex2: 更新矩阵
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = A * (1/A).sum(axis = 1).reshape(-1,1)
B

array([[1.83333333, 3.66666667, 5.5       ],
       [2.46666667, 3.08333333, 3.7       ],
       [2.65277778, 3.03174603, 3.41071429]])

In [111]:
# Ex3: 卡方统计量
np.random.seed(0)
A = np.random.randint(10,20,(8,5))
B = A.sum(0) * A.sum(1).reshape(-1,1) / A.sum()
res = ((A - B) ** 2 / B).sum()
res

np.float64(11.842696601945802)

In [112]:
# Ex4: 改进矩阵计算的性能
# 原方法
np.random.seed(0)
m, n , p = 100, 80, 50
B = np.random.randint(0,2,(m,p))
U = np.random.randint(0,2,(p,n))
Z = np.random.randint(0,2,(m,n))
def solution(B, U, Z):
    L_res = []
    for i in range(m):
        for j in range(n):
            norm_value = ((B[i,:] - U[:,j]) ** 2).sum()
            L_res.append(norm_value* Z[i,j])

    return sum(L_res)
solution(B, U, Z)

np.int64(100566)

In [113]:
# 改进方法
(((B**2).sum(1).reshape(-1,1) + (U**2).sum(0) - 2 * B @ U) * Z).sum()

np.int64(100566)

In [114]:
# 对比性能
%timeit -n 30 solution(B, U, Z)

18.4 ms ± 427 μs per loop (mean ± std. dev. of 7 runs, 30 loops each)


In [115]:
%timeit -n 30 (((B**2).sum(1).reshape(-1,1) + (U**2).sum(0) - 2 * B @ U) * Z).sum()

204 μs ± 30.5 μs per loop (mean ± std. dev. of 7 runs, 30 loops each)


In [120]:
# Ex5:连续整数的最大长度
f = lambda x : np.diff(np.nonzero(np.r_[1, np.diff(x) != 1 ,1])).max()
f([3,2,1,2,3,4,6])

np.int64(4)