## 二、Numpy基础
### 1.np数组的构造

In [4]:
# 最一般的方式是通过array来构造
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [5]:
# 下面讨论一些特殊数组的生成方式
# a.等差序列：np.linspace;np.arange
np.linspace(1,5,11) # 起始、终止（包含）、样本个数

array([1. , 1.4, 1.8, 2.2, 2.6, 3. , 3.4, 3.8, 4.2, 4.6, 5. ])

In [6]:
np.arange(1,5,2) # 起始、终止（不包含）、步长

array([1, 3])

In [7]:
# b.特殊矩阵：zeros, eye, full
np.zeros((2,3)) # 传入元组表示各维度大小

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.eye(3) # 3*3的单位矩阵

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [9]:
np.eye(3,k = 1) # 偏移主对角线1个单位的伪单位矩阵

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [10]:
np.full((2,3),10) # 元组传入大小,10为填充值

array([[10, 10, 10],
       [10, 10, 10]])

In [11]:
np.full((2,3),[1,2,3]) # 每行填入相同的列表

array([[1, 2, 3],
       [1, 2, 3]])

In [12]:
# c.随机矩阵: np.random
# 最常用的随机生成函数为rand,randn, randint,choice,它们分别表示0-1均匀分布的随机数组，标准正态分布的随机数组，随机整数组和随机列表抽样：
np.random.rand(3) # 3个0-1均匀分布的随机数

array([0.20528528, 0.02017853, 0.52180116])

In [13]:
np.random.rand(3,3) # 3*3的0-1均匀分布随机矩阵

array([[0.07464807, 0.46602449, 0.77230185],
       [0.54934929, 0.17661442, 0.57601503],
       [0.36367762, 0.5320297 , 0.47917693]])

In [14]:
# 对于服从区间a到b上的均匀分布可以如下生成：
a, b = 5, 15
(b-a) * np.random.rand(3) + a  # 3个服从a到b均匀分布的随机数

array([13.18064994,  6.8596637 ,  7.35640808])

In [16]:
# 一般地，可以选择已有的库函数：
np.random.uniform(5,15,3)  # 3个服从5到15均匀分布的随机数

array([5.72747991, 7.04305979, 8.52612648])

In [17]:
# randn生成N(0,1)的标准正态分布:
np.random.randn(3)

array([0.31958996, 1.35495479, 0.11588977])

In [18]:
np.random.randn(2,2) # 2*2标准正态分布随机矩阵

array([[-0.71266969, -0.46010687],
       [-0.80847811,  0.45621275]])

In [19]:
# 对于服从方差为σ²，均值为μ的正态分布N(μ,σ²)的随机数，可以通过如下变换得到：
sigma, mu = 2.5, 3
mu + sigma * np.random.randn(3)

array([2.80714773, 8.24919609, 4.20626567])

In [20]:
# 同样的，也可以通过已有的库函数生成：
np.random.normal(3,2.5,3)  # 3个服从N(3,2.5²)的随机数

array([-1.1361075 , -1.10522319,  0.83871516])

In [ ]:
# randint可以指定生成随机整数的最小值最大值（不包含）和维度大小：
low, high, size = 5, 15, (2,2) # 生成2*2的5到14之间的随机整数矩阵
np.random.randint(low, high, size)

array([[ 5, 14],
       [12,  9]], dtype=int32)

In [23]:
# choice可以从给定的列表中，以一定概率和方式抽取结果，当不指定概率时为均匀采样，默认抽取方式为有放回抽样：
my_list = ['a','b','c','d']
np.random.choice(my_list, 2, replace = False, p = [0.1,0.7,0.1,0.1]) # 从my_list中无放回抽取2个元素，且'b'被抽中的概率为0.7

array(['a', 'b'], dtype='<U1')

In [24]:
np.random.choice(my_list,(3,3)) # 有放回抽取3*3元素矩阵

array([['a', 'b', 'b'],
       ['b', 'c', 'a'],
       ['a', 'a', 'c']], dtype='<U1')

In [25]:
# 当返回的元素个数与原列表相同时，不放回抽样等价于使用permutation函数，即打散原列表：
np.random.permutation(my_list)

array(['c', 'b', 'd', 'a'], dtype='<U1')

In [26]:
# 最后需要提到的是随机种子，它能够固定随机数的输出结果:
np.random.seed(0)
np.random.rand()

0.5488135039273248

In [27]:
np.random.seed(0)
np.random.rand()

0.5488135039273248