In [ ]:
import torch

a = [[1.,-1.],[-1.,1.]]
b = [[1,2,3],[4,5,6]]
#  (function) def tensor(
#     data: Any,
#     dtype: dtype | None = None,
#     device: DeviceLikeType | None = None,
#     requires_grad: bool = False,
#     pin_memory: bool = False
# ) -> Tensor
tensor_a = torch.tensor(a)
tensor_b = torch.tensor(b)
print(tensor_a,tensor_a.dtype,tensor_a.shape)
print(tensor_b,tensor_b.dtype ,tensor_b.shape)

tensor([[ 1., -1.],
        [-1.,  1.]]) torch.float32 torch.Size([2, 2])
tensor([[1, 2, 3],
        [4, 5, 6]]) torch.int64 torch.Size([2, 3])


In [5]:
import numpy as np

c = np.array([[1,2,3],[4,5,6]])
tensor_c = torch.from_numpy(c)
# 需要特别注意的是，创建的tensor和原array共享同一块内存，当修改其中一个的值时，另一个的值也会发生改变
print(tensor_c,tensor_c.dtype,tensor_c.shape)
c[0,0] = 0
print(tensor_c)

tensor([[1, 2, 3],
        [4, 5, 6]]) torch.int64 torch.Size([2, 3])
tensor([[0, 2, 3],
        [4, 5, 6]])


In [8]:
o_t = torch.tensor([1.])
t = torch.zeros((3,3),out=o_t)
print(t,"\n",o_t)
print(id(t),"\n",id(o_t))
print(t.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
139778514466080 
 139778514466080
torch.float32


In [15]:
t1 = torch.tensor([[1,2,3],[4,5,6]])
t2 = torch.zeros_like(t1)
print(t2,t2.dtype)

t3 = torch.ones((2,2))
t4 = torch.ones_like(t1)
print(t3,t3.dtype)
print(t4,t4.dtype)

t5 = torch.full((4,4),7)
print(t5,t5.dtype)

t6 = torch.full_like(t1,8)
print(t6,t6.dtype)

tensor([[0, 0, 0],
        [0, 0, 0]]) torch.int64
tensor([[1., 1.],
        [1., 1.]]) torch.float32
tensor([[1, 1, 1],
        [1, 1, 1]]) torch.int64
tensor([[7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7],
        [7, 7, 7, 7]]) torch.int64
tensor([[8, 8, 8],
        [8, 8, 8]]) torch.int64


In [ ]:
t7 = torch.arange(0,10,2)  # 步长
print(t7,t7.dtype)

tensor([0, 2, 4, 6, 8]) torch.int64


In [ ]:
t8 = torch.linspace(0,10,5)  # 个数
print(t8,t8.dtype)

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000]) torch.float32


In [ ]:
t9 = torch.logspace(0,10,5)  # 个数,默认底数为10
print(t9,t9.dtype)

tensor([1.0000e+00, 3.1623e+02, 1.0000e+05, 3.1623e+07, 1.0000e+10]) torch.float32


In [21]:
# 单位对角矩阵
l1 = torch.eye(3)
print(l1,l1.dtype)
l2 = torch.eye(3,4)
print(l2,l2.dtype)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]) torch.float32
tensor([[1., 0., 0., 0.],
        [0., 1., 0., 0.],
        [0., 0., 1., 0.]]) torch.float32


In [29]:
# torch.empty(*size, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor
# 返回一个未初始化的张量，包括size大小和dtype类型
l3 = torch.empty(2,3)
print(l3,l3.dtype)

# torch.empty_like(input, dtype=None, layout=None, device=None, requires_grad=False) → Tensor
# 返回一个未初始化的张量，包括input的size和dtype类型
l4 = torch.empty_like(l3)
print(l4,l4.dtype)

# torch.empty_strided(size, stride, out=None, dtype=None, layout=torch.strided, device=None, requires_grad=False) → Tensor
# 返回一个未初始化的张量，包括size大小和dtype类型，stride步长
l5 = torch.empty_strided((2,3),(1,2))
print(l5,l5.dtype)

tensor([[ 7.3948e-13,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00, -8.6198e-05,  4.5604e-41]]) torch.float32
tensor([[7.2520e-13, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 7.2929e-13, 0.0000e+00]]) torch.float32
tensor([[7.4437e-13, 0.0000e+00, 4.4842e-44],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]]) torch.float32


In [ ]:
# 依概率分布创建
# torch.normal(mean, std, out=None) → Tensor
# mean为张量，std为张量
n1 = torch.normal(torch.zeros(3),torch.ones(3))
print(n1,n1.dtype)


tensor([ 0.6536, -1.7524, -0.3140]) torch.float32


In [ ]:
n2 = torch.rand((3,3))  # 0-1均匀分布
print(n2,n2.dtype)

# torch.rand_like()

tensor([[0.3955, 0.5670, 0.7966],
        [0.4293, 0.4432, 0.6576],
        [0.4699, 0.0670, 0.2476]]) torch.float32


In [ ]:
n3 = torch.randint(0,10,(3,3))  # 0-10均匀分布
print(n3,n3.dtype)

n4 = torch.randint_like(n3,10)
print(n4,n4.dtype)

tensor([[7, 1, 8],
        [3, 2, 6],
        [1, 8, 2]]) torch.int64
tensor([[9, 8, 8],
        [1, 7, 2],
        [4, 6, 4]]) torch.int64


In [37]:
n5 = torch.randperm(10) # 随机排列
print(n5,n5.dtype)

tensor([8, 3, 6, 2, 5, 7, 0, 4, 1, 9]) torch.int64


In [ ]:
n6 = torch.bernoulli(torch.full((3,3),0.5))  # 伯努利分布 （0-1分布）
print(n6,n6.dtype)

tensor([[1., 0., 1.],
        [1., 1., 1.],
        [0., 1., 1.]]) torch.float32
