- torch.cat(tensors, dim=0, *, out=None) → Tensor

In [2]:
import torch

x = torch.randn(2,3)
print(x)

tensor([[-0.5127, -1.1283,  0.7264],
        [ 1.7375, -0.5123,  1.6377]])


In [6]:
torch.cat((x,x,x),0)

tensor([[-0.3990,  0.7104,  0.5715],
        [-0.0114,  0.1978,  1.9778],
        [-0.3990,  0.7104,  0.5715],
        [-0.0114,  0.1978,  1.9778],
        [-0.3990,  0.7104,  0.5715],
        [-0.0114,  0.1978,  1.9778]])

In [7]:
torch.cat((x,x,x),1)

tensor([[-0.3990,  0.7104,  0.5715, -0.3990,  0.7104,  0.5715, -0.3990,  0.7104,
          0.5715],
        [-0.0114,  0.1978,  1.9778, -0.0114,  0.1978,  1.9778, -0.0114,  0.1978,
          1.9778]])

- torch.split(tensor, split_size_or_sections, dim=0)

In [94]:
a = torch.arange(10).reshape(5,2)
print(a)

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])


In [95]:
# 如果 split_size_or_sections 是整数类型，则 tensor 将被拆分为大小相等的块（如果可能）。
# 如果沿给定维度 dim 的张量大小不能被 split_size 整除，则最后一个块将更小。
torch.split(a,2)

(tensor([[0, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7]]),
 tensor([[8, 9]]))

In [99]:
# 如果 split_size_or_sections 是一个列表，
# 那么 tensor 将根据 split_size_or_sections 被分成 len（split_size_or_sections） 个大小为 dim 的块。
torch.split(a,[1,4])

(tensor([[0, 1]]),
 tensor([[2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]))

- torch.chunk(input: Tensor, chunks: int, dim: int = 0) → Tuple[Tensor, ...]
- 尝试将张量拆分为指定数量的块。每个块都是输入张量的视图。

In [16]:
torch.arange(11).chunk(6)

(tensor([0, 1]),
 tensor([2, 3]),
 tensor([4, 5]),
 tensor([6, 7]),
 tensor([8, 9]),
 tensor([10]))

In [17]:
torch.arange(12).chunk(6)

(tensor([0, 1]),
 tensor([2, 3]),
 tensor([4, 5]),
 tensor([6, 7]),
 tensor([8, 9]),
 tensor([10, 11]))

In [100]:
torch.arange(13).chunk(6)

(tensor([0, 1, 2]),
 tensor([3, 4, 5]),
 tensor([6, 7, 8]),
 tensor([ 9, 10, 11]),
 tensor([12]))

- torch.tensor_split(input, indices_or_sections, dim=0) → List of Tensors
- 将一个张量拆分为多个子张量，所有这些子张量都是输入视图，根据 indices_or_sections 指定的索引或截面数沿维度 dim

In [19]:
x = torch.arange(8)
torch.tensor_split(x,3)

(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7]))

In [27]:
x = torch.arange(7)
torch.tensor_split(x,3)

(tensor([0, 1, 2]), tensor([3, 4]), tensor([5, 6]))

In [22]:
torch.tensor_split(x,(1,6)) # [:1],[1:6],[6:]

(tensor([0]), tensor([1, 2, 3, 4, 5]), tensor([6]))

In [29]:
x = torch.arange(14).reshape(2,7)
x

tensor([[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13]])

In [30]:
torch.tensor_split(x,3,dim = 1)

(tensor([[0, 1, 2],
         [7, 8, 9]]),
 tensor([[ 3,  4],
         [10, 11]]),
 tensor([[ 5,  6],
         [12, 13]]))

In [31]:
torch.tensor_split(x,(1,6),dim = 1)

(tensor([[0],
         [7]]),
 tensor([[ 1,  2,  3,  4,  5],
         [ 8,  9, 10, 11, 12]]),
 tensor([[ 6],
         [13]]))

- torch.stack(tensors, dim=0, *, out=None) → Tensor

In [35]:
x = torch.randn(2,3)
print(x,x.shape)

tensor([[ 1.3712, -0.6194,  1.6953],
        [-2.0196, -0.0571, -0.6183]]) torch.Size([2, 3])


In [36]:
print(torch.stack((x,x)),torch.stack((x,x)).shape)

tensor([[[ 1.3712, -0.6194,  1.6953],
         [-2.0196, -0.0571, -0.6183]],

        [[ 1.3712, -0.6194,  1.6953],
         [-2.0196, -0.0571, -0.6183]]]) torch.Size([2, 2, 3])


In [37]:
print(torch.stack((x,x),dim =1),torch.stack((x,x),dim =1).shape)

tensor([[[ 1.3712, -0.6194,  1.6953],
         [ 1.3712, -0.6194,  1.6953]],

        [[-2.0196, -0.0571, -0.6183],
         [-2.0196, -0.0571, -0.6183]]]) torch.Size([2, 2, 3])


In [40]:
print(torch.stack((x,x),dim = 2),torch.stack((x,x),dim = 2).shape)

tensor([[[ 1.3712,  1.3712],
         [-0.6194, -0.6194],
         [ 1.6953,  1.6953]],

        [[-2.0196, -2.0196],
         [-0.0571, -0.0571],
         [-0.6183, -0.6183]]]) torch.Size([2, 3, 2])


In [41]:
print(torch.stack((x,x),dim = -1),torch.stack((x,x),dim = -1).shape)

tensor([[[ 1.3712,  1.3712],
         [-0.6194, -0.6194],
         [ 1.6953,  1.6953]],

        [[-2.0196, -2.0196],
         [-0.0571, -0.0571],
         [-0.6183, -0.6183]]]) torch.Size([2, 3, 2])


In [44]:
print(torch.stack((x,x,x),dim = 2),torch.stack((x,x,x),dim = 2).shape)

tensor([[[ 1.3712,  1.3712,  1.3712],
         [-0.6194, -0.6194, -0.6194],
         [ 1.6953,  1.6953,  1.6953]],

        [[-2.0196, -2.0196, -2.0196],
         [-0.0571, -0.0571, -0.0571],
         [-0.6183, -0.6183, -0.6183]]]) torch.Size([2, 3, 3])


- torch.conj(input) → Tensor

In [46]:
x = torch.tensor([-1 + 1j, -2 + 2j,3 - 3j])
print(x.is_conj())
y =torch.conj(x)
print(y)
print(y.is_conj())

False
tensor([-1.-1.j, -2.-2.j,  3.+3.j])
True


- torch.dsplit(input, indices_or_sections) → List of Tensors

In [58]:
t = torch.arange(16.0).reshape(2,2,4)
t

tensor([[[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.]],

        [[ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]]])

In [ ]:
# 这等效于调用 torch.tensor_split（input， indices_or_sections， dim=2）（split dimension 为 2），
# 不同之处在于，如果 indices_or_sections 是整数，则必须均匀划分 split 维度，否则将引发运行时错误
torch.dsplit(t,2)
# torch.tensor_split(t,2,dim = 2)

(tensor([[[ 0.,  1.],
          [ 4.,  5.]],
 
         [[ 8.,  9.],
          [12., 13.]]]),
 tensor([[[ 2.,  3.],
          [ 6.,  7.]],
 
         [[10., 11.],
          [14., 15.]]]))

In [65]:
torch.dsplit(t,[3,6])

(tensor([[[ 0.,  1.,  2.],
          [ 4.,  5.,  6.]],
 
         [[ 8.,  9., 10.],
          [12., 13., 14.]]]),
 tensor([[[ 3.],
          [ 7.]],
 
         [[11.],
          [15.]]]),
 tensor([], size=(2, 2, 0)))

- torch.column_stack(tensors, *, out=None) → Tensor
- 等效于 torch.hstack（tensors），不同之处在于张量中的每个零维或一维张量 t 在水平堆叠之前首先重塑为 （t.numel（）， 1） 列。

In [66]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
torch.column_stack((a,b))

tensor([[1, 4],
        [2, 5],
        [3, 6]])

In [67]:
a = torch.arange(5)
b = torch.arange(10).reshape(5,2)
torch.column_stack((a,b,b))

tensor([[0, 0, 1, 0, 1],
        [1, 2, 3, 2, 3],
        [2, 4, 5, 4, 5],
        [3, 6, 7, 6, 7],
        [4, 8, 9, 8, 9]])

- torch.dstack(tensors, *, out=None) → Tensor
- 按顺序纵向堆叠张量（沿第三个轴）。
- 这相当于在 1-D 和 2-D 张量被 torch.atleast_3d（） 重塑后沿第三轴的串联。

In [102]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
print(torch.dstack((a,b)),torch.dstack((a,b)).shape)

tensor([[[1, 4],
         [2, 5],
         [3, 6]]]) torch.Size([1, 3, 2])


In [93]:
a = torch.tensor([[1],[2],[3]])
b = torch.tensor([[4],[5],[6]])
print(torch.dstack((a,b)),torch.dstack((a,b)).shape)

tensor([[[1, 4]],

        [[2, 5]],

        [[3, 6]]]) torch.Size([3, 1, 2])


- torch.atleast_3d(*tensors)
- 返回每个输入张量的 3 维视图，维度为零。具有三个或更多维度的输入张量按原样返回。

In [76]:
x = torch.tensor(0.5)
x

tensor(0.5000)

In [77]:
torch.atleast_3d(x)

tensor([[[0.5000]]])

In [78]:
y = torch.arange(4).view(2,2)
y

tensor([[0, 1],
        [2, 3]])

In [79]:
torch.atleast_3d(y)

tensor([[[0],
         [1]],

        [[2],
         [3]]])

In [80]:
x = torch.tensor(1).view(1,1,1)
x

tensor([[[1]]])

In [81]:
torch.atleast_3d(x)

tensor([[[1]]])

In [83]:
x = torch.tensor(0.5)
y = torch.tensor(1.0)
torch.atleast_3d((x,y))

(tensor([[[0.5000]]]), tensor([[[1.]]]))

- torch.gather(input, dim, index, *, sparse_grad=False, out=None) → Tensor
- 可以将这个过程理解为：索引张量告诉函数"从每行的哪个列位置提取元素"，然后将提取的元素放置在对应的输出位置上
- out[i][j][k] = input[index[i][j][k]][j][k]  # if dim == 0
- out[i][j][k] = input[i][index[i][j][k]][k]  # if dim == 1
- out[i][j][k] = input[i][j][index[i][j][k]]  # if dim == 2

In [3]:
t = torch.tensor([[1,2],[3,4]])
torch.gather(t,1,torch.tensor([[0,0],[1,0]]))

tensor([[1, 1],
        [4, 3]])

- torch.hsplit(input, indices_or_sections) → List of Tensors

In [4]:
t = torch.arange(16.0).reshape(4,4)
t

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

In [5]:
torch.hsplit(t,2)

(tensor([[ 0.,  1.],
         [ 4.,  5.],
         [ 8.,  9.],
         [12., 13.]]),
 tensor([[ 2.,  3.],
         [ 6.,  7.],
         [10., 11.],
         [14., 15.]]))

In [6]:
torch.hsplit(t,[3,6])

(tensor([[ 0.,  1.,  2.],
         [ 4.,  5.,  6.],
         [ 8.,  9., 10.],
         [12., 13., 14.]]),
 tensor([[ 3.],
         [ 7.],
         [11.],
         [15.]]),
 tensor([], size=(4, 0)))

- torch.hstack(tensors, *, out=None) → Tensor
- This is equivalent to concatenation along the first axis for 1-D tensors, and along the second axis for all other tensors

In [7]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
torch.hstack((a,b))

tensor([1, 2, 3, 4, 5, 6])

In [8]:
a = torch.tensor([[1],[2],[3]])
b = torch.tensor([[4],[5],[6]])
torch.hstack((a,b))

tensor([[1, 4],
        [2, 5],
        [3, 6]])

- torch.index_add(input: Tensor, dim: int, index: Tensor, source: Tensor, *, alpha: Union[Number, _complex] = 1, out: Optional[Tensor]) → Tensor
- Tensor.index_add_(dim, index, source, *, alpha=1) → Tensor
- self[index[i], :, :] += alpha * src[i, :, :]  # if dim == 0
- self[:, index[i], :] += alpha * src[:, i, :]  # if dim == 1
- self[:, :, index[i]] += alpha * src[:, :, i]  # if dim == 2

In [15]:
x = torch.ones(5,3)
t = torch.tensor([[1,2,3],[4,5,6],[7,8,9]],dtype=torch.float32)
index = torch.tensor([0,4,2])
x.index_add(0,index,t)

tensor([[ 2.,  3.,  4.],
        [ 1.,  1.,  1.],
        [ 8.,  9., 10.],
        [ 1.,  1.,  1.],
        [ 5.,  6.,  7.]])

In [16]:
x.index_add(0,index,t,alpha=-1)

tensor([[ 0., -1., -2.],
        [ 1.,  1.,  1.],
        [-6., -7., -8.],
        [ 1.,  1.,  1.],
        [-3., -4., -5.]])

- torch.index_copy(input: Tensor, dim: int, index: Tensor, source: Tensor, *, out: Optional[Tensor]) → Tensor


In [17]:
# 创建一个目标张量
input = torch.zeros(3, 5)
# 创建一个源张量，包含要复制的数据
source = torch.ones(2, 5)
# 指定索引位置
index = torch.tensor([0, 2])

# 在dim=0维度上，将source的数据复制到input的第0行和第2行
result = torch.index_copy(input, 0, index, source)
print(result)

tensor([[1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [1., 1., 1., 1., 1.]])


- torch.index_reduce(input: Tensor, dim: int, index: Tensor, source: Tensor, reduce: str, *, include_self: bool = True, out: Optional[Tensor]) → Tensor
- For a 3-D tensor with reduce="prod" and include_self=True the output is given as:   
self[index[i], :, :] *= src[i, :, :]  # if dim == 0   
self[:, index[i], :] *= src[:, i, :]  # if dim == 1   
self[:, :, index[i]] *= src[:, :, i]  # if dim == 2   

In [19]:
x = torch.empty(5,3).fill_(2)
t = torch.tensor([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],dtype=torch.float32)
index = torch.tensor([0,4,2,0])
x.index_reduce(0,index,t,'prod')

/tmp/ipykernel_40691/1925619273.py:4: UserWarning: index_reduce() is in beta and the API may change at any time. (Triggered internally at /pytorch/aten/src/ATen/native/TensorAdvancedIndexing.cpp:1218.)
  x.index_reduce(0,index,t,'prod')


tensor([[20., 44., 72.],
        [ 2.,  2.,  2.],
        [14., 16., 18.],
        [ 2.,  2.,  2.],
        [ 8., 10., 12.]])

In [ ]:
x.index_reduce(0,index,t,'prod',include_self=False)

tensor([[10., 22., 36.],
        [ 2.,  2.,  2.],
        [ 7.,  8.,  9.],
        [ 2.,  2.,  2.],
        [ 4.,  5.,  6.]])

- torch.index_select(input, dim, index, *, out=None) → Tensor

In [21]:
x = torch.randn(3,4)
x

tensor([[ 1.0257, -1.1746, -0.2725, -0.0853],
        [ 0.3084,  2.4357, -0.2500,  1.4339],
        [-0.1916,  0.9298, -0.2361,  1.4188]])

In [22]:
indices = torch.tensor([0,2])
torch.index_select(x,0,indices)

tensor([[ 1.0257, -1.1746, -0.2725, -0.0853],
        [-0.1916,  0.9298, -0.2361,  1.4188]])

In [23]:
torch.index_select(x,1,indices)

tensor([[ 1.0257, -0.2725],
        [ 0.3084, -0.2500],
        [-0.1916, -0.2361]])

- torch.masked_select(input, mask, *, out=None) → Tensor
- 返回一个新的 1-D 张量，该张量根据布尔掩码 mask 索引 input 张量，其中布尔掩码 mask 是一个 BoolTensor
- The shapes of the mask tensor and the input tensor don’t need to match, but they must be **broadcastable**

In [24]:
x = torch.randn(3,4)
x

tensor([[-0.9909, -1.6578, -0.7618, -0.4770],
        [ 1.0316, -1.6346, -0.8811,  0.4734],
        [ 1.9939, -0.2066, -0.3350,  0.7763]])

In [26]:
mask = x.ge(0.5)
mask

tensor([[False, False, False, False],
        [ True, False, False, False],
        [ True, False, False,  True]])

In [27]:
torch.masked_select(x,mask)

tensor([1.0316, 1.9939, 0.7763])

- torch.movedim(input, source, destination) → Tensor

In [1]:
import torch
t = torch.randn(3,2,1)
t

tensor([[[-0.9365],
         [ 0.6670]],

        [[-1.2468],
         [ 0.3878]],

        [[-1.2740],
         [-0.5295]]])

In [2]:
torch.movedim(t,1,0).shape

torch.Size([2, 3, 1])

In [3]:
torch.movedim(t,1,0)

tensor([[[-0.9365],
         [-1.2468],
         [-1.2740]],

        [[ 0.6670],
         [ 0.3878],
         [-0.5295]]])

In [4]:
torch.movedim(t,(1,2),(0,1)).shape

torch.Size([2, 1, 3])

In [5]:
torch.movedim(t,(1,2),(0,1))

tensor([[[-0.9365, -1.2468, -1.2740]],

        [[ 0.6670,  0.3878, -0.5295]]])

In [6]:
# 创建一个形状为 (2, 3, 4) 的张量
t = torch.arange(24).reshape(2, 3, 4)
print("原始张量:")
print(t)

# 使用 movedim
result = torch.movedim(t, (1, 2), (0, 1))
print("\n变换后张量:")
print(result)

# 验证特定元素位置
i, j, k = 1, 2, 3  # 原始位置
print(f"\n原始元素 t[{i},{j},{k}] = {t[i,j,k]}")
print(f"变换后位置 result[{j},{k},{i}] = {result[j,k,i]}")

原始张量:
tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

变换后张量:
tensor([[[ 0, 12],
         [ 1, 13],
         [ 2, 14],
         [ 3, 15]],

        [[ 4, 16],
         [ 5, 17],
         [ 6, 18],
         [ 7, 19]],

        [[ 8, 20],
         [ 9, 21],
         [10, 22],
         [11, 23]]])

原始元素 t[1,2,3] = 23
变换后位置 result[2,3,1] = 23


- torch.moveaxis(input, source, destination) → Tensor   
Alias for torch.movedim().

- torch.narrow(input, dim, start, length) → Tensor    
返回一个新张量，它是 input 张量的缩小版本。维度 dim 从 start 到 start + length 输入。返回的张量和 input 张量共享相同的底层存储。

In [9]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
torch.narrow(x,0,0,2)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
torch.narrow(x,-1,torch.tensor(-1),1)

tensor([[3],
        [6],
        [9]])

- torch.narrow_copy(input, dim, start, length, *, out=None) → Tensor
与 Tensor.narrow() 相同，但这个函数返回一个副本而不是共享存储。这主要用于稀疏张量，因为稀疏张量没有共享存储的 narrow 方法

In [14]:
x = torch.tensor([[1,2,3],[4,5,6],[7,8,9]])
torch.narrow_copy(x,0,0,2)

tensor([[1, 2, 3],
        [4, 5, 6]])

In [15]:
torch.narrow_copy(x,1,1,2)

tensor([[2, 3],
        [5, 6],
        [8, 9]])

In [16]:
s = torch.arange(16).reshape(2,2,2,2).to_sparse(2)
torch.narrow_copy(s,0,0,1)

tensor(indices=tensor([[0, 0],
                       [0, 1]]),
       values=tensor([[[0, 1],
                       [2, 3]],

                      [[4, 5],
                       [6, 7]]]),
       size=(1, 2, 2, 2), nnz=2, layout=torch.sparse_coo)

- torch.nonzero(input, *, out=None, as_tuple=False) → LongTensor or tuple of LongTensors

In [17]:
torch.nonzero(torch.tensor([1,1,1,0,1]))

tensor([[0],
        [1],
        [2],
        [4]])

In [18]:
torch.nonzero(torch.tensor([[0.6, 0.0, 0.0, 0.0],
                            [0.0, 0.4, 0.0, 0.0],
                            [0.0, 0.0, 0.2, 0.0],
                            [0.0, 0.0, 0.0, -0.4]]))

tensor([[0, 0],
        [1, 1],
        [2, 2],
        [3, 3]])

In [19]:
torch.nonzero(torch.tensor([1,1,1,0,1]),as_tuple=True)

(tensor([0, 1, 2, 4]),)

In [20]:
torch.nonzero(torch.tensor(5),as_tuple=True)

(tensor([0]),)

- torch.permute(input, dims) → Tensor    
  返回原始张量 input 的维度置换视图

In [5]:
import torch
x = torch.randn(2,3,5)
x.size()
# x

torch.Size([2, 3, 5])

In [6]:
torch.permute(x,(2,0,1)).size()
# torch.permute(x,(2,0,1)) 

torch.Size([5, 2, 3])

- torch.reshape(input, shape) → Tensor    
  返回一个与 input 具有相同数据和元素数量的张量，但具有指定的形状。当可能时，返回的张量将是 input 的视图。否则，它将是一个副本。连续输入和具有兼容步长的输入可以在不复制的情况下进行重塑，但您不应依赖于复制与查看的行为

  查看 torch.Tensor.view() 了解何时可以返回视图

  单维可以是 -1，在这种情况下，它将从剩余维度和 input 中的元素数量推断出来

In [7]:
a = torch.arange(4,)
torch.reshape(a,(2,2))

tensor([[0, 1],
        [2, 3]])

In [8]:
b = torch.tensor([[0,1],[2,3]])
torch.reshape(b,(-1,))

tensor([0, 1, 2, 3])

- torch.row_stack(tensors, *, out=None) → Tensor    
  按行堆叠张量,即第一个维度上增加，等同于torch.vstack

In [10]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
torch.vstack((a,b))

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
a = torch.tensor([[1],[2],[3]])
b = torch.tensor([[4],[5],[6]])
torch.vstack((a,b))

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

- torch.scatter(input, dim, index, src) → Tensor
- torch.Tensor.scatter_的原地版本    
- Tensor.scatter_(dim, index, src, *, reduce=None) → Tensor  
- self[index[i][j][k]][j][k] = src[i][j][k]  # if dim == 0     
    
- self[i][index[i][j][k]][k] = src[i][j][k]  # if dim == 1    
    
- self[i][j][index[i][j][k]] = src[i][j][k]  # if dim == 2
    
这是 gather() 中描述的方法的逆操作

In [13]:
src = torch.arange(1,11).reshape((2,5))
src

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [14]:
index = torch.tensor([[0,1,2,0]])
torch.zeros(3,5,dtype = src.dtype).scatter_(0,index,src)

tensor([[1, 0, 0, 4, 0],
        [0, 2, 0, 0, 0],
        [0, 0, 3, 0, 0]])

In [20]:
index = torch.tensor([[0,1,2],[0,1,4]])
out = torch.zeros(3,5,dtype = src.dtype)
out_1= out.scatter_(1,index,src)
id(out),id(out_1)

(123803734258416, 123803734258416)

In [21]:
torch.full((2,4),2.).scatter_(1,torch.tensor([[2],[3]]),1.23,reduce='multiply')

tensor([[2.0000, 2.0000, 2.4600, 2.0000],
        [2.0000, 2.0000, 2.0000, 2.4600]])

In [23]:
torch.full((2,4),2.).scatter_(1,torch.tensor([[2],[3]]),1.23,reduce = 'add')

tensor([[2.0000, 2.0000, 3.2300, 2.0000],
        [2.0000, 2.0000, 2.0000, 3.2300]])

- torch.scatter_reduce(input, dim, index, src, reduce, *, include_self=True) → Tensor    
  Out-of-place version of torch.Tensor.scatter_reduce_() 

- Tensor.scatter_reduce_(dim, index, src, reduce, *, include_self=True) → Tensor     

- For a 3-D tensor with reduce="sum" and include_self=True the output is given as:    
- self[index[i][j][k]][j][k] += src[i][j][k]  # if dim == 0
- self[i][index[i][j][k]][k] += src[i][j][k]  # if dim == 1
- self[i][j][index[i][j][k]] += src[i][j][k]  # if dim == 2



In [1]:
import torch
src = torch.tensor([1.,2.,3.,4.,5.,6.])
index = torch.tensor([0,1,0,1,2,1])
input = torch.tensor([1.,2.,3.,4.])
input.scatter_reduce_(0,index,src,reduce="sum")

tensor([ 5., 14.,  8.,  4.])

In [2]:
input.scatter_reduce_(0,index,src,reduce="sum",include_self=False)

tensor([ 4., 12.,  5.,  4.])

In [4]:
input2 = torch.tensor([5.,4.,3.,2.])
input2.scatter_reduce(0,index,src,reduce="amax")

tensor([5., 6., 5., 2.])

In [5]:
input2.scatter_reduce(0,index,src,reduce="amax",include_self=False)

tensor([3., 6., 5., 2.])

- torch.split(tensor, split_size_or_sections, dim=0)
- 将张量分割成块。每个块都是原始张量的视图
- 如果 split_size_or_sections 是整数类型，则 tensor 将被分割成大小相等的块（如果可能的话）。如果沿着给定维度 dim 的张量大小不能被 split_size 整除，最后一个块将更小
- 如果 split_size_or_sections 是一个列表，则 tensor 将根据 split_size_or_sections 分割成 len(split_size_or_sections) 块，块的大小为 dim

In [1]:
import torch
a = torch.arange(10).reshape(5,2)
a

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [ ]:
torch.split(a,2)

(tensor([[0, 1],
         [2, 3]]),
 tensor([[4, 5],
         [6, 7]]),
 tensor([[8, 9]]))

In [8]:
torch.split(a,[1,4])

(tensor([[0, 1]]),
 tensor([[2, 3],
         [4, 5],
         [6, 7],
         [8, 9]]))

- torch.squeeze(input: Tensor, dim: Optional[Union[int, List[int]]]) → Tensor
- 返回一个移除了所有指定维度的 input ，大小为 1 的张量

In [9]:
x = torch.zeros(2,1,2,1,2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [10]:
y = torch.squeeze(x)
y.size()

torch.Size([2, 2, 2])

In [13]:
y = torch.squeeze(x,0)
y.size()

torch.Size([2, 1, 2, 1, 2])

In [15]:
y = torch.squeeze(x,1)
y.size()

torch.Size([2, 2, 1, 2])

In [17]:
y = torch.squeeze(x,(1,2,3))
y.size()

torch.Size([2, 2, 2])

- torch.stack(tensors, dim=0, *, out=None) → Tensor
- 连接一系列张量沿新维度
- 所有张量的大小必须相同

In [20]:
x = torch.randn(2,3)
x

tensor([[-0.4267, -0.7573,  1.2053],
        [-0.4606,  0.9043,  1.0584]])

In [23]:
torch.stack((x,x)).size()

torch.Size([2, 2, 3])

In [24]:
torch.stack((x,x),dim = 1)

tensor([[[-0.4267, -0.7573,  1.2053],
         [-0.4267, -0.7573,  1.2053]],

        [[-0.4606,  0.9043,  1.0584],
         [-0.4606,  0.9043,  1.0584]]])

In [25]:
torch.stack((x,x),dim = 2 )

tensor([[[-0.4267, -0.4267],
         [-0.7573, -0.7573],
         [ 1.2053,  1.2053]],

        [[-0.4606, -0.4606],
         [ 0.9043,  0.9043],
         [ 1.0584,  1.0584]]])

In [26]:
torch.stack((x,x),dim = -1)

tensor([[[-0.4267, -0.4267],
         [-0.7573, -0.7573],
         [ 1.2053,  1.2053]],

        [[-0.4606, -0.4606],
         [ 0.9043,  0.9043],
         [ 1.0584,  1.0584]]])

- torch.swapaxes(input, axis0, axis1) → Tensor
- 等价于torch.transpose()

In [30]:
x = torch.tensor([[[0,1],[2,3]],[[4,5],[6,7]]])
x

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])

In [31]:
torch.swapaxes(x,0,1)

tensor([[[0, 1],
         [4, 5]],

        [[2, 3],
         [6, 7]]])

In [32]:
torch.swapaxes(x,0,2)

tensor([[[0, 4],
         [2, 6]],

        [[1, 5],
         [3, 7]]])

- torch.swapdims(input, dim0, dim1) → Tensor
- 等价于torch.transpose()

In [33]:
x= torch.tensor([[[0,1],[2,3]],[[4,5],[6,7]]])
x 

tensor([[[0, 1],
         [2, 3]],

        [[4, 5],
         [6, 7]]])

In [34]:
torch.swapdims(x,0,1)

tensor([[[0, 1],
         [4, 5]],

        [[2, 3],
         [6, 7]]])

In [35]:
torch.swapdims(x,0,2)

tensor([[[0, 4],
         [2, 6]],

        [[1, 5],
         [3, 7]]])

- torch.t(input) → Tensor         转置
- 0-D 和 1-D 张量按原样返回,当输入是 2-D 张量时，这相当于 transpose(input, 0, 1) 

In [ ]:
x = torch.randn(())
x

tensor(-0.1906)

In [37]:
torch.t(x)

tensor(-0.1906)

In [39]:
x = torch.randn(3)
x

tensor([-0.2924, -0.5149,  0.5470])

In [40]:
torch.t(x)

tensor([-0.2924, -0.5149,  0.5470])

In [41]:
x = torch.rand(2,3)
x

tensor([[0.6929, 0.3914, 0.9603],
        [0.5505, 0.3372, 0.4796]])

In [42]:
torch.t(x)

tensor([[0.6929, 0.5505],
        [0.3914, 0.3372],
        [0.9603, 0.4796]])

- torch.take(input, index) → Tensor
- 返回一个新张量，其中包含 input 在给定索引处的元素。输入张量被视为一个 1 维张量。结果与索引具有相同的形状

In [43]:
src = torch.tensor([[4,3,5],[6,7,8]])

In [44]:
torch.take(src,torch.tensor([0,2,5]))

tensor([4, 5, 8])

- torch.take_along_dim(input, indices, dim=None, *, out=None) → Tensor
- 选择从给定维度 dim 沿着 1 维索引从 indices 中选取 input 的值
- 如果 dim 为 None，则输入数组被视为已展平为 1d

In [45]:
t = torch.tensor([[10,30,20],[60,40,50]])
max_idx = torch.argmax(t)
torch.take_along_dim(t,max_idx)

tensor([60])

In [46]:
sorted_idx = torch.argsort(t,dim = 1)
torch.take_along_dim(t,sorted_idx,dim = 1)

tensor([[10, 20, 30],
        [40, 50, 60]])

- torch.argmax(input) → LongTensor
- 返回 input 张量中所有元素的最大值的索引
- 如果有多个最大值，则返回第一个最大值的索引

In [48]:
a = torch.randn(4,4)
a

tensor([[-0.3641, -0.5941, -0.5726, -0.0680],
        [-0.2770,  1.1013,  0.8363, -0.6711],
        [-0.2892,  0.0470, -0.0367, -1.8883],
        [ 0.3052, -0.9223, -2.2735, -0.8262]])

In [49]:
torch.argmax(a)

tensor(5)

- torch.argmax(input, dim, keepdim=False) → LongTensor
- 返回张量沿某一维度的最大值的索引
- keepdim（bool）- 输出张量是否保留了 dim 维度

In [50]:
a = torch.randn(4,4)
a

tensor([[-0.5474, -0.9632, -0.2224,  0.3720],
        [ 1.2053,  0.3507, -0.1909, -0.6335],
        [-0.0159, -1.9765, -0.5542,  0.6149],
        [-0.8622, -0.7681,  0.5811, -2.1430]])

In [53]:
torch.argmax(a,dim = 1)

tensor([3, 0, 3, 2])

In [54]:
torch.argmax(a,dim = 1,keepdim=True)

tensor([[3],
        [0],
        [3],
        [2]])

- torch.argsort(input, dim=-1, descending=False, stable=False) → Tensor
- 返回沿给定维度按值升序排序张量的索引

In [55]:
a = torch.rand(4,4)
a

tensor([[0.3800, 0.0587, 0.3440, 0.2428],
        [0.1172, 0.5859, 0.0466, 0.0329],
        [0.6791, 0.1541, 0.9897, 0.2742],
        [0.6557, 0.6340, 0.6577, 0.1743]])

In [56]:
torch.argsort(a,dim = 1 )

tensor([[1, 3, 2, 0],
        [3, 2, 0, 1],
        [1, 3, 0, 2],
        [3, 1, 0, 2]])

- torch.tensor_split(input, indices_or_sections, dim=0) → List of Tensors
- 将张量分割成多个子张量，所有子张量都是 input 的视图，根据 indices_or_sections 指定的索引或段数，沿维度 dim 进行分割
- 如果 indices_or_sections 是一个整数 n 或一个值为 n 的零维长张量， input 将沿着维度 dim 被分割成 n 个部分。如果 input 沿着维度 dim 可以被 n 整除，每个部分将具有相同的大小，即 input.size(dim) / n 。如果 input 不能被 n 整除，前 int(input.size(dim) % n) 个部分的大小将为 int(input.size(dim) / n) + 1 ，其余部分的大小将为 int(input.size(dim) / n) 
- 如果 indices_or_sections 是一个整数列表或元组，或者是一个一维长张量，那么 input 将沿着维度 dim 在每个列表、元组或张量中的索引处进行分割。例如， indices_or_sections=[2, 3] 和 dim=0 将产生张量 input[:2] 、 input[2:3] 和 input[3:]
- 如果 indices_or_sections 是一个张量，它必须在 CPU 上是一个零维或一维长张量

In [3]:
import torch
x = torch.arange(8)
torch.tensor_split(x,3)

(tensor([0, 1, 2]), tensor([3, 4, 5]), tensor([6, 7]))

In [4]:
x = torch.arange(7)
torch.tensor_split(x,3)

(tensor([0, 1, 2]), tensor([3, 4]), tensor([5, 6]))

In [5]:
torch.tensor_split(x,(1,6))

(tensor([0]), tensor([1, 2, 3, 4, 5]), tensor([6]))

In [6]:
x = torch.arange(14).reshape(2,7)
x

tensor([[ 0,  1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12, 13]])

In [7]:
torch.tensor_split(x,3,dim = 1)

(tensor([[0, 1, 2],
         [7, 8, 9]]),
 tensor([[ 3,  4],
         [10, 11]]),
 tensor([[ 5,  6],
         [12, 13]]))

In [8]:
torch.tensor_split(x,(1,6),dim = 1)

(tensor([[0],
         [7]]),
 tensor([[ 1,  2,  3,  4,  5],
         [ 8,  9, 10, 11, 12]]),
 tensor([[ 6],
         [13]]))

- torch.tile(input, dims) → Tensor
- 构建通过重复 input 的元素来构造张量的操作,dims 参数指定了每个维度中的重复次数
- 如果 dims 指定的维度少于 input 的维度，则将 1 prepended 到 dims ，直到指定所有维度。例如，如果 input 的形状为(8, 6, 4, 2)，而 dims 为(2, 2)，则 dims 被视为(1, 1, 2, 2)
- 类似地，如果 input 的维度少于 dims 指定的维度，则 input 被视为在零维度上未挤压，直到它具有 dims 指定的维度数。例如，如果 input 的形状为(4, 2)，而 dims 为(3, 3, 2, 2)，则 input 被视为具有形状(1, 1, 4, 2)

In [9]:
x = torch.tensor([1,2,3])
x.tile((2,))

tensor([1, 2, 3, 1, 2, 3])

In [10]:
y = torch.tensor([[1,2],[3,4]])
torch.tile(y,(2,2))

tensor([[1, 2, 1, 2],
        [3, 4, 3, 4],
        [1, 2, 1, 2],
        [3, 4, 3, 4]])

- torch.transpose(input, dim0, dim1) → Tensor

In [12]:
x = torch.randn(2,3)
x

tensor([[ 0.7196,  0.6288,  1.3664],
        [-1.5834,  0.9597, -0.6937]])

In [13]:
torch.transpose(x,0,1)

tensor([[ 0.7196, -1.5834],
        [ 0.6288,  0.9597],
        [ 1.3664, -0.6937]])

- torch.unbind(input, dim=0) → seq
- 移除张量维度
- 返回一个元组，包含给定维度上的所有切片，且已不包括该维度

In [14]:
torch.unbind(torch.tensor([[1,2,3],
                           [4,5,6],
                           [7,8,9]]))

(tensor([1, 2, 3]), tensor([4, 5, 6]), tensor([7, 8, 9]))

- torch.unsqueeze(input, dim) → Tensor
- 返回一个新的张量，在指定位置插入一个大小为 1 的维度
- 返回的张量与这个张量共享相同的基本数据
- 可以使用范围 [-input.dim() - 1, input.dim() + 1) 内的 A dim 值。负 dim 将对应于在 dim = dim + input.dim() + 1 时应用的 unsqueeze()

In [15]:
x = torch.tensor([1,2,3,4])
torch.unsqueeze(x,0)

tensor([[1, 2, 3, 4]])

In [16]:
torch.unsqueeze(x,1)

tensor([[1],
        [2],
        [3],
        [4]])

- torch.vsplit(input, indices_or_sections) → List of Tensors
- 将 input （一个具有两个或更多维度的张量）根据 indices_or_sections 垂直分割成多个张量。每个分割都是 input 的视图
- 这是调用 torch.tensor_split(input, indices_or_sections, dim=0)（分割维度为 0）的等效操作，但如果有 0#是一个整数，它必须能够整除分割维度，否则将抛出运行时错误

In [17]:
t = torch.arange(16.0).reshape(4,4)
t

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.]])

In [21]:
torch.vsplit(t,2)

(tensor([[0., 1., 2., 3.],
         [4., 5., 6., 7.]]),
 tensor([[ 8.,  9., 10., 11.],
         [12., 13., 14., 15.]]))

In [19]:
torch.vsplit(t,[3,6])

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]),
 tensor([[12., 13., 14., 15.]]),
 tensor([], size=(0, 4)))

- torch.vstack(tensors, *, out=None) → Tensor
- 垂直（按行）堆叠张量序列
- 这是在所有一维张量通过 torch.atleast_2d() 重塑后沿第一个轴进行连接的等效操作

In [22]:
a = torch.tensor([1,2,3])
b = torch.tensor([4,5,6])
torch.vstack((a,b))

tensor([[1, 2, 3],
        [4, 5, 6]])

In [23]:
a = torch.tensor([[1],[2],[3]])
b = torch.tensor([[4],[5],[6]])
torch.vstack((a,b))

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

- torch.where(condition, input, other, *, out=None) → Tensor
- 返回一个张量，其中包含从 input 或 other 中选择的元素，具体取决于 condition
- 张量 condition 、 input 、 other 必须可广播

In [24]:
x = torch.randn(3,2)
y = torch.ones(3,2)
x

tensor([[ 1.2104, -0.5108],
        [ 0.3742,  1.8345],
        [ 0.3634,  0.3075]])

In [25]:
torch.where(x > 0,1.0,0.0)

tensor([[1., 0.],
        [1., 1.],
        [1., 1.]])

In [26]:
torch.where(x > 0, x, y)

tensor([[1.2104, 1.0000],
        [0.3742, 1.8345],
        [0.3634, 0.3075]])

In [27]:
x = torch.randn(2,2,dtype = torch.double)
x

tensor([[ 1.6143,  0.2004],
        [-1.1056, -1.5155]], dtype=torch.float64)

In [28]:
torch.where(x > 0,x,0.)

tensor([[1.6143, 0.2004],
        [0.0000, 0.0000]], dtype=torch.float64)

- torch.where(condition) → tuple of LongTensor
- torch.where(condition) is identical to torch.nonzero(condition, as_tuple=True)

- torch.seed()      获取一个随机的随机种子
- torch.manual_seed()    手动设置随机种子，建议设置为42
- torch.initial_seed()    返回初始种子
- torch.get_rng_state()       获取随机数生成器状态
- operations on cpu

张量的数学操作包含以下：
- Pointwise操作     逐元素的操作，如abs, cos, sin, floor, floor_divide, pow等
- Reduction操作     减少元素的操作，如argmax, argmin, all, any, mean, norm, var等
- Comparsion操作    对比操作， 如ge, gt, le, lt, eq, argsort, isnan, topk
- Spectral操作      谱操作，如短时傅里叶变换等各类信号处理的函数
- Other操作         其它， clone， diag，flip等
- BLAS and LAPACK操作    BLAS（Basic Linear Algebra Subprograms）基础线性代数）操作。如, addmm, dot, inner, svd等